package bs.cm.model;

public class Csrelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column csrelation.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column csrelation.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column csrelation.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column csrelation.customerid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column csrelation.serviceid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer serviceid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column csrelation.sid
	 * @return  the value of csrelation.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column csrelation.sid
	 * @param sid  the value for csrelation.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column csrelation.id
	 * @return  the value of csrelation.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column csrelation.id
	 * @param id  the value for csrelation.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column csrelation.userid
	 * @return  the value of csrelation.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column csrelation.userid
	 * @param userid  the value for csrelation.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column csrelation.customerid
	 * @return  the value of csrelation.customerid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column csrelation.customerid
	 * @param customerid  the value for csrelation.customerid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column csrelation.serviceid
	 * @return  the value of csrelation.serviceid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getServiceid() {
		return serviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column csrelation.serviceid
	 * @param serviceid  the value for csrelation.serviceid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}
}