package bs.cm.model;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.name
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.mobile
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.qq
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.address
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.remark
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.pinyin
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String pinyin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.initials
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String initials;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.sid
	 * @return  the value of customer.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.sid
	 * @param sid  the value for customer.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.id
	 * @return  the value of customer.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.id
	 * @param id  the value for customer.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.userid
	 * @return  the value of customer.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.userid
	 * @param userid  the value for customer.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.name
	 * @return  the value of customer.name
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.name
	 * @param name  the value for customer.name
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.mobile
	 * @return  the value of customer.mobile
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.mobile
	 * @param mobile  the value for customer.mobile
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.qq
	 * @return  the value of customer.qq
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.qq
	 * @param qq  the value for customer.qq
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.address
	 * @return  the value of customer.address
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.address
	 * @param address  the value for customer.address
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.remark
	 * @return  the value of customer.remark
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.remark
	 * @param remark  the value for customer.remark
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.pinyin
	 * @return  the value of customer.pinyin
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getPinyin() {
		return pinyin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.pinyin
	 * @param pinyin  the value for customer.pinyin
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.initials
	 * @return  the value of customer.initials
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getInitials() {
		return initials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.initials
	 * @param initials  the value for customer.initials
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setInitials(String initials) {
		this.initials = initials;
	}
}