package bs.cm.model;

public class Service {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service.name
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service.price
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service._desc
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String desc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service.sid
	 * @return  the value of service.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service.sid
	 * @param sid  the value for service.sid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service.id
	 * @return  the value of service.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service.id
	 * @param id  the value for service.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service.userid
	 * @return  the value of service.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service.userid
	 * @param userid  the value for service.userid
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service.name
	 * @return  the value of service.name
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service.name
	 * @param name  the value for service.name
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service.price
	 * @return  the value of service.price
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service.price
	 * @param price  the value for service.price
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service._desc
	 * @return  the value of service._desc
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service._desc
	 * @param desc  the value for service._desc
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	
}