package bs.cm.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.accountname
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String accountname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.accountname
	 * @return  the value of user.accountname
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getAccountname() {
		return accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.accountname
	 * @param accountname  the value for user.accountname
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	private String sessionToken;
	
	public String getSessionToken() {
		return sessionToken;
	}

	public void setSessionToken(String sessionToken) {
		this.sessionToken = sessionToken;
	}
}