package bs.cm.mapper;

import java.util.List;

import bs.cm.model.Csrelation;

public interface CsrelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table csrelation
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table csrelation
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int insert(Csrelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table csrelation
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int insertSelective(Csrelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table csrelation
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	Csrelation selectByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table csrelation
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int updateByPrimaryKeySelective(Csrelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table csrelation
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int updateByPrimaryKey(Csrelation record);

	List<Csrelation> selectAll();
	List<Csrelation> selectByUserid(Integer userid);
}