package bs.cm.mapper;

import java.util.List;

import bs.cm.model.Customer;

public interface CustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int insert(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int insertSelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	Customer selectByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int updateByPrimaryKeySelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int updateByPrimaryKey(Customer record);

	List<Customer> selectAll();
	List<Customer> selectByUserid(Integer userid);
}