package bs.cm.mapper;

import java.util.List;

import bs.cm.model.Service;

public interface ServiceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int insert(Service record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int insertSelective(Service record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	Service selectByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int updateByPrimaryKeySelective(Service record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed May 20 23:02:27 CST 2015
	 */
	int updateByPrimaryKey(Service record);

	List<Service> selectAll();
	List<Service> selectByUserid(Integer userid);
}